name: Build Package

on:
  workflow_call:
    secrets:
      CF_API_KEY:
        required: true

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v6

      - name: Run LuaCheck
        uses: BigWigsMods/actions/luacheck@master
        with:
          config: https://raw.githubusercontent.com/SFX-WoW/shared/main/config/.luacheckrc

      - name: Run Packager
        uses: BigWigsMods/packager@v2
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
        with:
          args: -a 0 -w 0 -L
